accounts:
  - handle: miramurati
  - handle: btaylor
  - handle: claybavor
  - handle: jainarvind
  - handle: seb_ruder
  - handle: karpathy
  - handle: demishassabis
  - handle: darioamodei
  - handle: danielaamodei
  - handle: sama
  - handle: elonmusk
  - handle: sergeykarayev
  - handle: ylecun
  - handle: mustafasuleyman
  - handle: ilyasut
  - handle: deedydas
  - handle: naval
  - handle: chamath
  - handle: dharmesh
